version: "3"

services:
    telegram-mastodon-bridge:
      build:
        context: "."
        dockerfile: Dockerfile
      container_name: telegram-mastodon-bridge
      network_mode: "host" # for ssl magic
      environment:
        - MASTODON_TOKEN=${MASTODON_TOKEN}
        - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
        - MASTODON_INSTANCE=${MASTODON_INSTANCE}
        - MASTODON_VISIBILITY=${MASTODON_VISIBILITY}
        - MASTODON_CHARACTER_LIMIT=500
      restart: always
